
services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    working_dir: /app

  worker:
    build: .
    command: celery -A celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: postgres_supabase
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: supabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery_worker
    command: celery -A celery_app worker --loglevel=info
    working_dir: /app
    depends_on:
      - redis
      - app
    environment:
      - PYTHONPATH=/app
      - HTTP_PROXY=
      - HTTPS_PROXY=
      - NO_PROXY=localhost,127.0.0.1,host.docker.internal
    volumes:
      - .:/app
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 1.1.1.1

volumes:
  pgdata: